YAMYAM/src/main/resources/static/css/styles.css
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html

2022-11-14

---

YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

생산(soram3)
1. proPlan.html 내용 수정
2. layout.html 수정 : date-picker, selectbox style css 추가
3. planOrdCheck.html 추가

20221114_생산관리,생산지시관리,조회

---

YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

1. common.js 추가
2. layout.html 변경
3. proPlan.html 프론트 완성
4. plandOrd~, proOrder.html 수정

생산(soram6)

---

YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/static/js/tui-grid.js
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

1.layout.html toastr 추가
2.tui-grid.js 수정
3. commons.js (var Grid = tui.Grid; Grid.setLanguage('ko');) 수정

생산(soram7)

---

YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matLookup.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matReturn.html
YAMYAM/src/main/resources/templates/mat/matReturnLookup.html
YAMYAM/src/main/resources/templates/mat/matSafe.html
YAMYAM/src/main/resources/templates/mat/matStockLookup.html

자재 자바스크립트 코드 정리 완료.
h3로 통일 완료.
*내일 할 일*
DB에 이름 겹치는 컬럼 이름 수정하고 데이터 받아오기~

2022-11-16 마지막

---

YAMYAM/src/main/resources/static/css/styles.css
YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/static/js/tui-grid.js
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

생산(soram8)
1. [jquery_confirm](http://myclabs.github.io/jquery.confirm/) 공부하기 - sweetAlert2으로 수정(입력,수정,삭제에 대하여)
2. common.js : sweetAlert2 함수 추가 → 페이지에서 confirm들 수정
3. tui-grid.js : select All → 전체로 변경
4. 생산계획관리 페이지 : 등록탭에서 생산요청서 조회에서 선택된 행 그리드에 출력
5. 생산관리 : layout href 연결 변경
6. style h4 폰트 스타일 추가
7. 생산 관리 진행중

# 2022/11/17

---

YAMYAM/src/main/resources/templates/order/odAd.html

11/17 주문 관리 디테일 수정 (그리드 추가)

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdList.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html
YAMYAM/src/main/resources/templates/order/prdReAd.html
YAMYAM/src/main/resources/templates/order/prdSfamtAd.html

영업관리 탭 전체 앞단 완성 (90%)
(ahhyun7)

11/18 영업관리 탭 전체 앞단 완성

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/monitoring.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html
YAMYAM/src/main/resources/templates/production/proResult.html

1. 생산 관리 진행 중
1) layout.html :  href연결 수정
2.  common.js 수정
1) function sweetConfirm 수정
2) datepicker 관련 함수 수정
1. front 대충.. 완성..,,,,
영업(ahhyun7)
1. prdSfamtAd.html 생성
2. 영업 관리 전체 탭 앞단 완성 (90%)
미완성 기능은 DB 구현 시, 마무리

생산(soram9)

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matOd.html

2022-11-18

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/proPlan.html

2)생산계획테이블(P_PLN)과 상세생산계획(P_PLND) 테이블에서 계획등록일자 컬럼명 수정 ( PPLN_DAYS → PPLN_DATE)
3. 생산지시테이블(P_OD) 추가 [계획등록일자 컬럼명 수정 ( PPLND_DATE → PPLN_DATE)]
4. proVO , mapper, service 생성
5. 생산계획(관리탭)
1) 조회 (where 날짜 : 기능 구현하기..,,,)
2) update 구현
3) 삭제 → 해야함
6. 생산요청서 목록 조회 (납기일자 형식 바꿔야함)

1)생산계획테이블(P_PLN)에서 완제품 코드 제거

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matLookup.html
YAMYAM/src/main/resources/templates/mat/matOd.html

1)자재 발주 관리 일반 탭 남은 작업
추가 -> 발주코드는 insert 시 자동으로 입력되도록 처리해야함.
삭제 -> null 담기는 #{value}
저장 -> 아직 미처리
2)자재 발주 관리 생산계획서용 탭 남은 작업
자재발주에 안전발주량 계산되어 나오도록.
저장 -> 자재발주가 저장되도록.

2022-11-21 1:31

---

YAMYAM/src/main/java/com/mandu/yamyam/eqp/web/EqpController.java
YAMYAM/src/main/resources/templates/eqp/eqpAd.html
YAMYAM/src/main/resources/templates/eqp/eqpChkAd.html
YAMYAM/src/main/resources/templates/eqp/uopAd.html
YAMYAM/src/main/resources/templates/layout/layout.html

1120 비가동관리 점검관리

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/EmpVO.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/CommController.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/comm/commCodeAD.html
YAMYAM/src/main/resources/templates/comm/employeeAD.html
YAMYAM/src/main/resources/templates/comm/matCodeAD.html

2022-11-22 직원관리 수정, 삭제 구현.

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

1. 생산 관리 페이지 끝
2. 생산지시페이지 관리 진행중..

생산(soram12)

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matLookup.html
YAMYAM/src/main/resources/templates/mat/matOd.html

1. 자재발주관리
2. 자재발주조회
완성 ^^ /*******

2022-11-23

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdVO.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html

11/23 완제품출고조회 완성, 주문관리 디테일 수정 출고관리, 반품관리 기능 구현중

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

생산(soram14)

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matReturn.html
YAMYAM/src/main/resources/templates/mat/matReturnLookup.html
YAMYAM/src/main/resources/templates/mat/matSafe.html
YAMYAM/src/main/resources/templates/mat/matStockLookup.html

5번탭 진행 중
자재 출고/ 반품 더미데이터 작업해야 함.

2022-11-24

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html

1. 생산 지시 C 끝
2. 생산 지시 입력될때 상세생산계획에 진행구분 업데이트 완료
3. 자재 리스트 업데이트… 고민중… ing…,,,,,
4. 지시 조회 끝

생산(soram15)

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html
YAMYAM/src/main/resources/templates/production/proResult.html

1. 생산지시 입력시 자재 업데이트 고민듕 → 완료

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdVO.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html

11/24 주문관리, 완제품 출고 조회Tab 초기화버튼, radio 버튼 수정, 완제품 출고 관리 Tab lot Modal 수정중

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html

1. 제품공정흐름도관리 행 삭제 > update / 행 추가 후 저장 > update
2. 생산공정 이거저거...

생산(soram18)

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatVO.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html

2022-11-25

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html

11/25 영업관리 commit

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html

11/25 영업관리 출고수정중

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/resources/templates/order/prdOutAd.html

11/25 출고 재수정

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html

# 2022/11/25

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/static/js/common.js
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proResult.html

생산(soram20)
1. 생산 관리 : setInterval() 하는 중 → 완료
2. 생산 관리 : b-in table insert 하는 중..
3. 공정실적조회 : ajax 조회 연결해야함

# 2022/11/26

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matReturn.html
YAMYAM/src/main/resources/templates/mat/matReturnLookup.html
YAMYAM/src/main/resources/templates/mat/matSafe.html
YAMYAM/src/main/resources/templates/mat/matStockLookup.html

1차 완성.
남은 일
1번 탭 안전발주량 넣어야함.
빠진 부분 체크 및 디테일 잡기.

2022-11-27

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdList.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html
YAMYAM/src/main/resources/templates/order/prdReAd.html

11/28 영업관리 전체 Tab 수정

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matLookup.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html

전체 확인하며 수정할 거 찾아서 수정 작업 진행 중.
시큐리티 아직 추가하지 않음. 화요일 오후에 추가 예정. ^0^ /

2022-11-28

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdVO.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdReAd.html
YAMYAM/src/main/resources/templates/order/prdSfamtAd.html

11/28 안전재고 관리 Tab, 반품 관리 Tab 수정

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/resources/static/css/styles.css
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/monitoring.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proOrder.html
YAMYAM/src/main/resources/templates/production/proPlan.html
YAMYAM/src/main/resources/templates/production/proResult.html

생산(soram23)
1. 시큐리티 적용중
2. css 로그인 색상 수정 로그아웃 색상 수정

#2022-11-28

---

YAMYAM/src/main/resources/templates/comm/BOMAD.html
YAMYAM/src/main/resources/templates/comm/actCodeAD.html
YAMYAM/src/main/resources/templates/comm/commCodeAD.html
YAMYAM/src/main/resources/templates/comm/matCodeAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-11-28 시큐리티 post에 모두 적용 (BOM.html은 아직 안만들어서 적용 안함)

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdList.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html
YAMYAM/src/main/resources/templates/order/prdReAd.html
YAMYAM/src/main/resources/templates/order/prdSfamtAd.html

11/28 영업관리 시큐리티 적용, 내용 간단 수정중

---

YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matSafe.html

2022-11-29

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/EmpController.java
YAMYAM/src/main/resources/templates/comm/BOMAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-11-29 일단 6장 완성 불안정한거 수정 예정

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html

11/29 영업관리 테스트 후, 수정작업

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProService.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/ProVO.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/web/ProController.java
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html
YAMYAM/src/main/resources/templates/production/proResult.html

생산(soram24)
1. 생산공정 이력 테이블 추가
2. 이거저거 수정중..

# 2022/11/29

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/EmpMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/EmpController.java
YAMYAM/src/main/resources/templates/comm/BOMAD.html
YAMYAM/src/main/resources/templates/comm/employeeAD.html
YAMYAM/src/main/resources/templates/comm/matCodeAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-11-29 저녁(정렬, 기능 확인 했음)

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/prdList.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdReAd.html

11/29 재고 조회까지 수정 완료

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matSafe.html
YAMYAM/src/main/resources/templates/mat/matStockLookup.html

1) 자재 재고 관리 체크, 언체크 이벤트 추가.
2) 메뉴 이름 변경
자재 재고 관리
LOT별 재고 조회

2022-11-30

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdList.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html
YAMYAM/src/main/resources/templates/order/prdReAd.html
YAMYAM/src/main/resources/templates/order/prdSfamtAd.html

11/30 영업 마무리

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/EmpController.java
YAMYAM/src/main/resources/templates/comm/BOMAD.html
YAMYAM/src/main/resources/templates/comm/matCodeAD.html

2022-11-30(아침 수정 완료!)

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/resources/templates/production/flowDiagram.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proManage.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html

생산(soram27)

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/OrdService.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/service/impl/OrdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/ord/web/OrdController.java
YAMYAM/src/main/resources/templates/order/prdAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html

영업 마무리 수정 완료!

---

YAMYAM/src/main/resources/templates/production/proOrdManage.html

#생산(soram28)

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proPlan.html

#생산(soram29)

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/EmpMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/MtrVO.java
YAMYAM/src/main/resources/templates/comm/matCodeAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-11-30(오류 수정 완료)!

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatOdService.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/MatVO.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/service/impl/MatOdServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/mat/web/MatController.java
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matOd.html

1) 입고되면 상세생산계획 테이블의 진행구분이 미지시로 업데이트 되도록 수정.
2) 자재발주쪽 단가 땡겨오는 함수 만들어서 적용.
3) 입고검수관리 페이지 입력칸 최소화 작업.

2022-12-01

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/resources/templates/production/planOrdCheck.html

생산(soram30)

---

YAMYAM/src/main/java/com/mandu/yamyam/ord/mapper/OrdMapper.xml
YAMYAM/src/main/resources/templates/order/odAd.html
YAMYAM/src/main/resources/templates/order/podOrderAd.html
YAMYAM/src/main/resources/templates/order/prdOutAd.html
YAMYAM/src/main/resources/templates/order/prdOutList.html

12/01 영업관리 통합 테스트 후, 수정

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/ActVO.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/EmpController.java
YAMYAM/src/main/resources/templates/comm/actCodeAD.html
YAMYAM/src/main/resources/templates/comm/commCodeAD.html
YAMYAM/src/main/resources/templates/comm/matCodeAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-12-01 수정완료!

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/resources/static/css/tui-grid.css
YAMYAM/src/main/resources/templates/layout/layout.html
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html

#2022.12.01

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matSafe.html

2022-12-02

---

YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/mapper/CommMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/CommService.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/service/impl/CommServiceImpl.java
YAMYAM/src/main/java/com/mandu/yamyam/comm/web/EmpController.java
YAMYAM/src/main/resources/templates/comm/BOMAD.html
YAMYAM/src/main/resources/templates/comm/pdtCodeAD.html

2022-12-02 수정완료!

---

YAMYAM/src/main/java/com/mandu/yamyam/mat/mapper/MatOdMapper.xml
YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matReturn.html
YAMYAM/src/main/resources/templates/mat/matSafe.html

1) 입고검수관리 담당자 "박자재"가 기본 값으로 변경.
2) 입고검수관리 추가 모달창 체크박스 추가, 닫기 버튼 추가.
3) 입고검수관리 행 추가 시 단 건과 다 건 체크 된 채로 추가되도록 변경.
4) 입고 관리 단 건에 대해서 동일하게 변경.

2022-12-04

---

YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proResult.html

생산(soram38)
1. 생산 관리 수정
2. mapper.xml :  생산 관리[진행 생산 지시] 오늘 날짜 관련
3. 공정 실적 조회 : 불량 없음으로 조회 수정

# 2022/12/05

---

YAMYAM/src/main/resources/templates/mat/matIn.html
YAMYAM/src/main/resources/templates/mat/matInChk.html
YAMYAM/src/main/resources/templates/mat/matInOut.html
YAMYAM/src/main/resources/templates/mat/matLookup.html
YAMYAM/src/main/resources/templates/mat/matOd.html
YAMYAM/src/main/resources/templates/mat/matOut.html
YAMYAM/src/main/resources/templates/mat/matReturn.html
YAMYAM/src/main/resources/templates/mat/matReturnLookup.html
YAMYAM/src/main/resources/templates/mat/matSafe.html
YAMYAM/src/main/resources/templates/mat/matStockLookup.html

2022-12-06

---

YAMYAM/src/main/java/com/mandu/yamyam/pro/mapper/ProMapper.xml
YAMYAM/src/main/java/com/mandu/yamyam/pro/service/impl/ProServiceImpl.java
YAMYAM/src/main/resources/templates/production/planOrdCheck.html
YAMYAM/src/main/resources/templates/production/proOrdManage.html
YAMYAM/src/main/resources/templates/production/proPlan.html
YAMYAM/src/main/resources/templates/production/proResult.html

#2022/12/06
